name: Build and Deploy
on:
  push:
    branches:
      - newCI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies for site/POM/Functions
        run: npm run installAll

      - name: Build hosting
        run: npm run buildAll

      - name: Archive site dist folder
        uses: actions/upload-artifact@master
        with:
          name: siteDist
          path: hosting/site/js/dist

      - name: Archive POM dist folder
        uses: actions/upload-artifact@master
        with:
          name: siteDist
          path: hosting/POM/js/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}